[2025-06-26T04:53:06.029+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.s3_upload manual__2025-06-26T04:53:01.738473+00:00 [queued]>
[2025-06-26T04:53:06.034+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.s3_upload manual__2025-06-26T04:53:01.738473+00:00 [queued]>
[2025-06-26T04:53:06.035+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-06-26T04:53:06.041+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): s3_upload> on 2025-06-26 04:53:01.738473+00:00
[2025-06-26T04:53:06.046+0000] {standard_task_runner.py:57} INFO - Started process 268 to run task
[2025-06-26T04:53:06.049+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_reddit_pipeline', 's3_upload', 'manual__2025-06-26T04:53:01.738473+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmptl1g9otk']
[2025-06-26T04:53:06.051+0000] {standard_task_runner.py:85} INFO - Job 50: Subtask s3_upload
[2025-06-26T04:53:06.086+0000] {task_command.py:416} INFO - Running <TaskInstance: etl_reddit_pipeline.s3_upload manual__2025-06-26T04:53:01.738473+00:00 [running]> on host f892d2298fb9
[2025-06-26T04:53:06.140+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Paresh Jadhav' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='s3_upload' AIRFLOW_CTX_EXECUTION_DATE='2025-06-26T04:53:01.738473+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-26T04:53:01.738473+00:00'
[2025-06-26T04:53:06.220+0000] {logging_mixin.py:151} INFO - <botocore.client.S3 object at 0xffff74b3f3d0>
[2025-06-26T04:53:07.296+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/aws_s3_pipline.py", line 9, in upload_s3_pipeline
    create_bucket_if_not_exists(s3, AWS_BUCKET_NAME)
  File "/opt/airflow/etls/aws_etl.py", line 48, in create_bucket_if_not_exists
    s3.head_bucket(Bucket=bucket_name)
  File "/home/airflow/.local/lib/python3.9/site-packages/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/botocore/client.py", line 928, in _make_api_call
    api_params = self._emit_api_params(
  File "/home/airflow/.local/lib/python3.9/site-packages/botocore/client.py", line 1043, in _emit_api_params
    self.meta.events.emit(
  File "/home/airflow/.local/lib/python3.9/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/botocore/handlers.py", line 278, in validate_bucket_name
    if not VALID_BUCKET.search(bucket) and not VALID_S3_ARN.search(bucket):
TypeError: expected string or bytes-like object
[2025-06-26T04:53:07.309+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=etl_reddit_pipeline, task_id=s3_upload, execution_date=20250626T045301, start_date=20250626T045306, end_date=20250626T045307
[2025-06-26T04:53:07.318+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 50 for task s3_upload (expected string or bytes-like object; 268)
[2025-06-26T04:53:07.351+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-06-26T04:53:07.365+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
