[2025-06-25T18:19:01.822+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.s3_upload manual__2025-06-25T18:18:56.601101+00:00 [queued]>
[2025-06-25T18:19:01.828+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.s3_upload manual__2025-06-25T18:18:56.601101+00:00 [queued]>
[2025-06-25T18:19:01.829+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-06-25T18:19:01.835+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): s3_upload> on 2025-06-25 18:18:56.601101+00:00
[2025-06-25T18:19:01.841+0000] {standard_task_runner.py:57} INFO - Started process 214 to run task
[2025-06-25T18:19:01.844+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_reddit_pipeline', 's3_upload', 'manual__2025-06-25T18:18:56.601101+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmp1aka3d9i']
[2025-06-25T18:19:01.847+0000] {standard_task_runner.py:85} INFO - Job 44: Subtask s3_upload
[2025-06-25T18:19:01.890+0000] {task_command.py:416} INFO - Running <TaskInstance: etl_reddit_pipeline.s3_upload manual__2025-06-25T18:18:56.601101+00:00 [running]> on host f892d2298fb9
[2025-06-25T18:19:01.948+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Paresh Jadhav' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='s3_upload' AIRFLOW_CTX_EXECUTION_DATE='2025-06-25T18:18:56.601101+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-25T18:18:56.601101+00:00'
[2025-06-25T18:19:01.962+0000] {logging_mixin.py:151} INFO - <s3fs.core.S3FileSystem object at 0xffff75438e50>
[2025-06-25T18:19:04.439+0000] {aws_etl.py:24} INFO - bucket named reddit-engineering-bkt already exists!
[2025-06-25T18:19:04.746+0000] {aws_etl.py:33} ERROR - Error uploading file to s3
[2025-06-25T18:19:04.747+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/s3fs/core.py", line 706, in _lsdir
    async for c in self._iterdir(
  File "/home/airflow/.local/lib/python3.9/site-packages/s3fs/core.py", line 756, in _iterdir
    async for i in it:
  File "/home/airflow/.local/lib/python3.9/site-packages/aiobotocore/paginate.py", line 30, in __anext__
    response = await self._make_request(current_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/aiobotocore/client.py", line 383, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/aws_s3_pipline.py", line 10, in upload_s3_pipeline
    upload_to_s3(s3, file_path, AWS_BUCKET_NAME, file_path.split('/')[-1])
  File "/opt/airflow/etls/aws_etl.py", line 34, in upload_to_s3
    raise e
  File "/opt/airflow/etls/aws_etl.py", line 30, in upload_to_s3
    s3.put(file_path, bucket+'/raw/'+ s3_file_name)
  File "/home/airflow/.local/lib/python3.9/site-packages/fsspec/asyn.py", line 118, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/fsspec/asyn.py", line 103, in sync
    raise return_result
  File "/home/airflow/.local/lib/python3.9/site-packages/fsspec/asyn.py", line 56, in _runner
    result[0] = await coro
  File "/home/airflow/.local/lib/python3.9/site-packages/fsspec/asyn.py", line 536, in _put
    trailing_sep(rpath) or await self._isdir(rpath)
  File "/home/airflow/.local/lib/python3.9/site-packages/s3fs/core.py", line 1411, in _isdir
    return bool(await self._lsdir(path))
  File "/home/airflow/.local/lib/python3.9/site-packages/s3fs/core.py", line 719, in _lsdir
    raise translate_boto_error(e)
PermissionError: Access Denied
[2025-06-25T18:19:04.762+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=etl_reddit_pipeline, task_id=s3_upload, execution_date=20250625T181856, start_date=20250625T181901, end_date=20250625T181904
[2025-06-25T18:19:04.768+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 44 for task s3_upload (Access Denied; 214)
[2025-06-25T18:19:04.785+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-06-25T18:19:04.800+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
